    SELECT nombre FROM producto;
    SELECT nombre, precio FROM producto;
    SELECT * FROM producto;
    SELECT nombre, CONCAT(precio, " €"), concat(round(precio*1.21,2), "$") FROM producto;
    SELECT nombre AS "nom del producte", CONCAT(precio, " €") AS "euros", concat(round(precio*1.21,2), "$") AS "dòlars" FROM producto;
    SELECT  UPPER(nombre) AS "producto",  precio FROM producto;
    SELECT  LOWER(nombre) AS "producto",  precio FROM producto;
    SELECT nombre, SUBSTR(nombre,1, 2)  FROM fabricante;
    SELECT nombre, round(precio, 1) AS "precio" FROM producto;
    SELECT nombre, round(precio) AS "precio" FROM producto;
    SELECT f.codigo FROM fabricante AS f, producto AS p  WHERE f.codigo = p.codigo_fabricante;
    SELECT f.codigo FROM fabricante as f, producto as p  WHERE f.codigo = p.codigo_fabricante GROUP BY f.codigo;
    SELECT nombre FROM fabricante ORDER BY nombre ASC;
    SELECT nombre FROM fabricante ORDER BY nombre DESC;
    SELECT nombre, precio FROM fabricante ORDER BY nombre ASC,  precio DESC ;
    SELECT * FROM fabricante LIMIT 5;
    SELECT * FROM fabricante LIMIT 3, 2;
    SELECT nombre, MIN(precio) AS 'precio más barato' FROM producto; 
    SELECT nombre, precio AS 'precio más caro' FROM producto ORDER BY precio DESC LIMIT 1;
    SELECT nombre FROM producto  WHERE codigo_fabricante = 2;
    SELECT p.nombre, p.precio, f.nombre FROM producto AS p, fabricante as f WHERE p.codigo_fabricante = f.codigo;
    SELECT p.nombre, p.precio, f.nombre FROM producto AS p, fabricante as f WHERE p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC;
    SELECT p.codigo_fabricante, p.nombre, f.codigo, f.nombre FROM producto AS p, fabricante as f WHERE p.codigo_fabricante = f.codigo;
    SELECT p.nombre, p.precio AS 'precio más barato', f.nombre AS 'fabricante' FROM producto AS p, fabricante as f WHERE p.codigo_fabricante = f.codigo ORDER BY precio ASC LIMIT 1;
    SELECT p.nombre, p.precio AS 'precio más caro', f.nombre AS 'fabricante' FROM producto AS p, fabricante as f WHERE p.codigo_fabricante = f.codigo ORDER BY precio DESC LIMIT 1;
    SELECT p.nombre, p.precio  FROM producto AS p JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = "Lenovo";
    SELECT p.nombre, max(p.precio) AS maximo  FROM producto AS p JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = "Crucial";
    SELECT p.nombre, p.precio, f.nombre  FROM producto AS p JOIN fabricante AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = "Asus" || f.nombre = "Hewlett-Packard";
    SELECT 	p.nombre, f.nombre as "fabricante" FROM fabricante f JOIN producto p ON f.codigo = p.codigo wHERE f.nombre IN('Asus', 'Seagate', 'Hewlett-Packard');
    SELECT 	p.nombre, p.precio, f.nombre as "fabricante" FROM fabricante f JOIN producto p ON f.codigo = p.codigo WHERE f.nombre LIKE '%e';
    SELECT 	p.nombre, p.precio, f.nombre as "fabricante" FROM fabricante f JOIN producto p ON f.codigo = p.codigo WHERE f.nombre LIKE '%w%';
    SELECT 	p.nombre, p.precio, f.nombre as "fabricante" FROM fabricante f JOIN producto p ON f.codigo = p.codigo WHERE p.precio > 180 ORDER BY p.precio DESC, p.nombre ASC;
    SELECT f.codigo, f.nombre FROM fabricante f JOIN producto  p ON f.codigo = p.codigo_fabricante GROUP BY f.nombre; ; 
    SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto  p ON f.codigo = p.codigo_fabricante ;
    SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto  p ON f.codigo = p.codigo_fabricante WHERE p.codigo is NULL;
    SELECT p.nombre, f.nombre from fabricante f,  producto p WHERE f.nombre = 'Lenovo' and f.codigo =  p.codigo_fabricante ;
    SELECT p.nombre, f.nombre, p.precio from fabricante f,  producto p WHERE  p.precio = (SELECT max(p.precio) from fabricante f,  producto p WHERE f.nombre = 'Lenovo' ) AND f.codigo =  p.codigo_fabricante;
